# SPDX-FileCopyrightText: Fedora Atomic Desktops maintainers
# SPDX-License-Identifier: CC0-1.0

name: "Build buildroot container image for Fedora Forge CI"

env:
  CONTAINERFILE: "./Containerfile"
  REGISTRY: "quay.io/operatement"
  NAME: "fedora-atomic-desktops-buildroot"
  BASEIMAGE_REPO: "quay.io/fedora/fedora-minimal"
  COSIGN_REPO: "ghcr.io/sigstore/cosign/cosign"
  COSIGN_TAG: "v2.6.2"
  CHUNKAH_REPO: "quay.io/coreos/chunkah"
  CHUNKAH_TAG: "dev"
  NODEJS_VERSION: "24"

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"
  schedule:
    - cron:  "0 6 * * *"
  workflow_dispatch:

permissions: read-all

# Prevent multiple workflow runs from racing to ensure that pushes are made
# sequentialy for the main branch. Also cancel in progress workflow runs.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-x86_64:
    runs-on: "ubuntu-24.04"
    container:
      image: quay.io/containers/podman:latest
      options: "--security-opt=label=disable --privileged --user 0:0 --device=/dev/kvm --device=/dev/fuse \
        --volume /:/run/host:rw --volume /mnt:/mnt --volume /var/run/docker.sock:/var/run/docker.sock \
        --workdir=/mnt"
    strategy:
      fail-fast: false
      matrix:
        release: ['rawhide', '44', '43']
    steps:
      - name: Prepare the graphroot storage location
        shell: bash
        run: |
          # Bind mount /mnt/containers over /var/lib/containers
          set -xeuo pipefail

          sudo ls -lah /var/lib/containers
          sudo mkdir --parents /mnt/containers
          sudo mount --bind /mnt/containers /var/lib/containers

          echo -e "\nAvailable disk storage:"
          sudo df --human-readable /var/lib/containers
          sudo df --human-readable /mnt/containers
          sudo lsblk --output NAME,PATH,TYPE,FSTYPE,SIZE,FSSIZE,FSUSED,FSAVAIL,FSUSE%,MOUNTPOINTS

      - name: Fixup GitHub homedir
        run: |
          set -xeuo pipefail
          mkdir -p /github/home/.docker/

      - name: Install tools in the container
        run: |
          set -xeuo pipefail
          export FORCE_COLUMNS=134
          rm --force /etc/yum.repos.d/fedora-cisco-openh264.repo
          dnf --refresh install --assumeyes --allowerasing \
            --no-allow-downgrade --no-docs --setopt=tsflags=nodocs \
            --setopt=install_weak_deps=False --best \
            --exclude container-selinux \
              buildah skopeo
          dnf clean all
          rm --recursive --force /tmp /var/lib/dnf /var/cache /var/log

      - name: "Checkout repo"
        uses: actions/checkout@v6

      - name: "Build container image"
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.NAME }}
          tags: ${{ matrix.release }}-x86_64
          containerfiles: ${{ env.CONTAINERFILE }}
          oci: true
          build-args: |
            BASEIMAGE_REPO=${{ env.BASEIMAGE_REPO }}
            BASEIMAGE_TAG=${{ matrix.release }}
            COSIGN_REPO=${{ env.COSIGN_REPO }}
            COSIGN_TAG=${{ env.COSIGN_TAG }}
            CHUNKAH_REPO=${{ env.CHUNKAH_REPO }}
            CHUNKAH_TAG=${{ env.CHUNKAH_TAG }}
            NODEJS_VERSION=${{ env.NODEJS_VERSION }}
          extra-args: |
            --skip-unused-stages=false
            --security-opt=label=type:unconfined_t
            --volume /__w/${{ github.event.repository.name }}/${{ github.event.repository.name }}:/run/src

      - name: "Login to Container Registry"
        uses: redhat-actions/podman-login@v1
        # if: (github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main'
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.BOT_USERNAME }}
          password: ${{ secrets.BOT_SECRET }}
          auth_file_path: /tmp/auth.json

      - name: "Push to Container Registry"
        uses: redhat-actions/push-to-registry@v2
        # if: (github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main'
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.BOT_USERNAME }}
          password: ${{ secrets.BOT_SECRET }}
          image: ${{ env.NAME }}
          tags: ${{ matrix.release }}-x86_64
          extra-args: |
            --compression-format=zstd
            --compression-level=20

  build-aarch64:
    runs-on: "ubuntu-24.04-arm"
    container:
      image: quay.io/containers/podman:latest
      options: "--security-opt=label=disable --privileged --user 0:0 --device=/dev/kvm --device=/dev/fuse \
        --volume /:/run/host:rw --volume /mnt:/mnt --volume /var/run/docker.sock:/var/run/docker.sock \
        --workdir=/mnt"
    strategy:
      fail-fast: false
      matrix:
        release: ['rawhide', '44', '43']
    steps:
      - name: Prepare the graphroot storage location
        shell: bash
        run: |
          # Bind mount /mnt/containers over /var/lib/containers
          set -xeuo pipefail

          sudo ls -lah /var/lib/containers
          sudo mkdir --parents /mnt/containers
          sudo mount --bind /mnt/containers /var/lib/containers

          echo -e "\nAvailable disk storage:"
          sudo df --human-readable /var/lib/containers
          sudo df --human-readable /mnt/containers
          sudo lsblk --output NAME,PATH,TYPE,FSTYPE,SIZE,FSSIZE,FSUSED,FSAVAIL,FSUSE%,MOUNTPOINTS

      - name: Fixup GitHub homedir
        run: |
          set -xeuo pipefail
          mkdir -p /github/home/.docker/

      - name: Install tools in the container
        run: |
          set -xeuo pipefail
          export FORCE_COLUMNS=134
          rm --force /etc/yum.repos.d/fedora-cisco-openh264.repo
          dnf --refresh install --assumeyes --allowerasing \
            --no-allow-downgrade --no-docs --setopt=tsflags=nodocs \
            --setopt=install_weak_deps=False --best \
            --exclude container-selinux \
              buildah skopeo
          dnf clean all
          rm --recursive --force /tmp /var/lib/dnf /var/cache /var/log

      - name: "Checkout repo"
        uses: actions/checkout@v6

      - name: "Build container image"
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.NAME }}
          tags: ${{ matrix.release }}-aarch64
          containerfiles: ${{ env.CONTAINERFILE }}
          oci: true
          build-args: |
            BASEIMAGE_REPO=${{ env.BASEIMAGE_REPO }}
            BASEIMAGE_TAG=${{ matrix.release }}
            COSIGN_REPO=${{ env.COSIGN_REPO }}
            COSIGN_TAG=${{ env.COSIGN_TAG }}
            CHUNKAH_REPO=${{ env.CHUNKAH_REPO }}
            CHUNKAH_TAG=${{ env.CHUNKAH_TAG }}
            NODEJS_VERSION=${{ env.NODEJS_VERSION }}
          extra-args: |
            --skip-unused-stages=false
            --security-opt=label=type:unconfined_t
            --volume /__w/${{ github.event.repository.name }}/${{ github.event.repository.name }}:/run/src

      - name: "Login to Container Registry"
        uses: redhat-actions/podman-login@v1
        # if: (github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main'
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.BOT_USERNAME }}
          password: ${{ secrets.BOT_SECRET }}
          auth_file_path: /tmp/auth.json

      - name: "Push to Container Registry"
        uses: redhat-actions/push-to-registry@v2
        id: "push"
        # if: (github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main'
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.BOT_USERNAME }}
          password: ${{ secrets.BOT_SECRET }}
          image: ${{ env.NAME }}
          tags: ${{ matrix.release }}-aarch64
          extra-args: |
            --compression-format=zstd
            --compression-level=20

  merge:
    runs-on: "ubuntu-24.04"
    needs:
      - "build-x86_64"
      - "build-aarch64"
    strategy:
      fail-fast: false
      matrix:
        release: ['rawhide', '44', '43']
    steps:
      - name: "Setup cosign"
        uses: sigstore/cosign-installer@v3.10.0
        # if: (github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main'

      - name: "Login to Container Registry"
        uses: redhat-actions/podman-login@v1
        # if: (github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main'
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.BOT_USERNAME }}
          password: ${{ secrets.BOT_SECRET }}
          auth_file_path: /tmp/auth.json

      - name: "Create multi-arch manifest"
        # if: (github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main'
        shell: bash
        run: |
          set -xeuo pipefail
          buildah manifest create \
            "${REGISTRY}/${NAME}:${RELEASE}" \
            "${REGISTRY}/${NAME}:${RELEASE}-x86_64" \
            "${REGISTRY}/${NAME}:${RELEASE}-aarch64"
        env:
          RELEASE: ${{ matrix.release }}

      - name: "Push to Container Registry"
        uses: redhat-actions/push-to-registry@v2
        id: "push"
        # if: (github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main'
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.BOT_USERNAME }}
          password: ${{ secrets.BOT_SECRET }}
          image: ${{ env.NAME }}
          tags: ${{ matrix.release }}
          extra-args: |
            --compression-format=zstd
            --compression-level=20

      - name: "Sign container image"
        # if: (github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main'
        run: |
          cosign sign --yes --recursive --key env://COSIGN_PRIVATE_KEY ${{ env.REGISTRY }}/${{ env.NAME }}@${{ steps.push.outputs.digest }}
        env:
          COSIGN_EXPERIMENTAL: false
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
